FROM rust:1.75.0-alpine3.19

WORKDIR /app

RUN cargo install trunk --version 0.18.7
RUN rustup target add wasm32-unknown-unknown

#RUN rustup component add rustfmt
#RUN rustup component add clippy-preview
