version: "3.8"
services:
  frontend:
    #image: teixo_yew:01
    volumes:
      - type: bind
        source: ../ # source is the source of the mount, a path on the host for a bind mount, or the name of a volume defined in the top-level volumes key. Not applicable for a tmpfs mount.
        target: /app # target is the container path where the volume is mounted
    build:
      dockerfile: ./Dockerfile.teixo #./Dockerfile.yew
    command: bash -c "cd ./app/ && trunk serve"

